### ISSUE TITLE
[BUG] Cleanup Instructor

### ISSUE THREAD

**Issue by stroblme** [cirKITers/mind-the-qapp#21]
After discovering a bug in #20, I think that the instructor deserves some further cleanup especially regarding unused initialization (e.g. optimizer not needed if we don't want to train the model).
This requires checking every usage of the instructor object and making sure that we use a common api (e.g. not using the underlying model attributes if those are propagated by the instructor.

**Comment by majafranz** [comment]
This should probably also be resolved, when integrating the qml-essentials with an additional cleanup. See #25
