### ISSUE TITLE
[FR] add the variance of the Fourier coefficients + documentation

### ISSUE THREAD

**Issue by majafranz** [cirKITers/mind-the-qapp#29]
requires 
- [x] #25 and 
- [x] #21
to be solved first

**Comment by stroblme** [comment]
for implementation see [cirKITers/disentangling-entanglement-in-qml](https://github.com/cirKITers/disentangling-entanglement-in-qml)

**Comment by stroblme** [comment]
- think about collapsible items

**Comment by stroblme** [comment]
it's been a while.. I guess this would go into the expressibility page.. e.g. instead of the KL divergence depending on the inputs @majafranz ?

**Comment by stroblme** [comment]
will close in favor of #47
